// Assemble matching/SPEC.md from the per-page sections in spec-sections/.
//
//   node matching/build-spec.mjs
//
// SPEC.md is the Phase 1 deliverable and the thing matching/gate.sh preflights
// against, so it is GENERATED rather than hand-maintained: edit the section
// file, rebuild. The page keys below must stay in sync with gate.sh's `run`
// calls — the preflight greps for `^##+ +<page>`, so a section whose heading
// drifts silently re-blocks its page.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const DIR = new URL(".", import.meta.url).pathname;
const SECTIONS = join(DIR, "spec-sections");

// Order = live's nav order, then the three detail templates.
const PAGES = [
  "home",
  "yfv",
  "our-team",
  "services",
  "atd",
  "contact",
  "team",
  "svc",
  "qa",
];

const parts = [];
const missing = [];

const chrome = join(SECTIONS, "_chrome.md");
if (existsSync(chrome)) parts.push(readFileSync(chrome, "utf8").trim());
else missing.push("_chrome");

for (const page of PAGES) {
  const file = join(SECTIONS, `${page}.md`);
  if (!existsSync(file)) {
    missing.push(page);
    continue;
  }
  const body = readFileSync(file, "utf8").trim();
  // The preflight greps `^##+ +<page>`; a section that does not open with its
  // own key would build fine here and then refuse at the gate, which is the
  // most confusing possible failure. Catch it now.
  if (!new RegExp(`^##+ +${page}( |$|\\b)`, "im").test(body)) {
    console.error(
      `WARNING: ${page}.md does not open with a '## ${page}' heading — gate.sh will still refuse this page.`,
    );
  }
  parts.push(body);
}

const header = `# Reference spec — beachfrontdentistry.com

GENERATED by \`node matching/build-spec.mjs\` from \`matching/spec-sections/\`.
Edit the section files, not this one.

This is the Phase 1 deliverable of the \`matching-a-page\` skill and the
precondition \`matching/gate.sh\` enforces: a page with no section here does not
get a geometry round (repo CLAUDE.md rule 2).

Every value should carry a \`beachfront.css:<line>\` citation or an explicit
\`[probed-only]\` mark. Uncited numbers are how wrong values shipped on this
project — see CLAUDE.md rule 1.

**The root-font ladder applies to every rem value on every page:** live steps
\`html{font-size}\` to 40px ≥993 / 32px 769–992 / 24px ≤768 while its class
rules break at 991/767/479, so each rem has THREE resolved sizes. Values below
are keyed to the gate matrix 1440 / 834 / 390.

`;

writeFileSync(join(DIR, "SPEC.md"), header + parts.join("\n\n---\n\n") + "\n");

const built = PAGES.length - missing.filter((m) => m !== "_chrome").length;
console.log(
  `SPEC.md built — ${built}/${PAGES.length} pages${missing.length ? `, MISSING: ${missing.join(", ")}` : ""}`,
);
process.exit(missing.length ? 1 : 0);
